### PR TITLE
detect if error is part of single pass experiment and funnel it to its own group

### PR DESCRIPTION
**Pull request by erwinmombay**
ill add the change to runtime shortly

### CODE REVIEW

**Comment by erwinmombay** [comment]
@jridgewell PTAL

**Comment by erwinmombay** [comment]
@jridgewell good q. i didn't want to lose the 1p/3p separation but i guess i could also just do sp1p/sp3p/mp1p/mp3p. Is that preferable ?

**Comment by jridgewell** [comment]
Sorry, I was thinking binary type. https://github.com/ampproject/amphtml/blob/master/src/error.js#L514

**Comment by jridgewell** [comment]
Do you need me to deploy?

**Comment by jridgewell** [comment]
Deploying now.

**Pull request merged**
